### ISSUE TITLE
At Address junk view due to space.

### ISSUE THREAD

**Issue by clivebluston** [ethereum/browser-solidity#247] opened 2016-09-20 14:26 UTC
When creating an object view using At Address one or more spaces in the given address causes a junk view to be seen.
Easily reproducible on any contract.
So 
0x38f160ad632409bfb18582241d9fd88c1a072b
will be fine, but
<space>0x38f160ad632409bfb18582241d9fd88c1a072b
will produce junk.
Happens in Firefox 47.0.1. Did not try other browsers.

**Comment by axic** [comment] 2016-10-08 13:15
Duplicate of #210.

**Closed by axic** 2016-10-08 13:15 UTC
Labels: bug
