### ISSUE TITLE
Stop hijacking CMD + F search shortcut so that users can search in source for a particular phrase.

### ISSUE THREAD

**Issue by stefek99** [ethereum/browser-solidity#894] opened 2017-11-06 16:52 UTC
What is happening currently: `CMD + F` does not nothing.

What should happen:

a) use browser built-in search function
b) implement your own, for instance just like Github

![image](https://user-images.githubusercontent.com/249703/32452912-e08117a6-c2e8-11e7-9e05-cdfc62be24b2.png)

---

`CMD + F` shortcut is not hijacked when pressed outside the editor, but then it does the search only on the visible chunk of text.

_(it doesn't search for terms that are not visible on the screen)_

**Comment by hiqua** [comment] 2017-11-14 11:24
Similar issue: on Linux, CTRL-F is not hijacked, but searches only in the displayed source code, not the full source code. For example, searching for "voted" with the Ballot.sol contract shown until line 31 returns two results, line 6 and 28, but no result after, e.g. line 35 is never reached by the search.

It makes it harder to search through the source code, and it is misleading when you are not aware of the bug.

**Comment by axic** [comment] 2017-11-14 12:16
Please refer to #147.

**Comment by yann300** [comment] 2017-11-27 17:05
is going to be addressed by https://github.com/ethereum/browser-solidity/pull/906

**Closed** 2017-12-13 14:02 UTC
Labels: enhancement

**Comment by hiqua** [comment] 2017-12-13 14:34
The problem is still there, but I'll report it in #147 as advised.

**Comment by yann300** [comment] 2017-12-13 14:42
it is not yet pushed to remix.ethereum.org but hopefully very soon
