### ISSUE TITLE
Getting -32603 when trying to deploy contract in live network

### ISSUE THREAD

**Issue by Betawi1** [ethereum/browser-solidity#1020] opened 2018-01-27 23:34 UTC
A contract can be deployed fine in Ropsten, but when trying to deploy in live network it returned a -32603 (server error, internal xml-rpc error)

**Comment by iurimatias** [comment] 2018-01-29 21:40
seems to be an issue in metamask, linking here for reference until we can confirm https://github.com/MetaMask/metamask-extension/issues/3117

**Comment by coopjc** [comment] 2018-01-29 22:49
The issue is with Metamask? Huh. That's weird. It was working fine just a few days ago and they haven't seemed to say anything about it.

**Comment by iurimatias** [comment] 2018-01-30 19:49
Closing. The issue has been reportedly fixed in infura.

**Closed by iurimatias** 2018-01-30 19:49 UTC

**Comment by rawadrifai** [comment] 2018-02-02 01:04
is this still going on? I'm running into the same issue, it was working fine yesterday.

**Comment by sameepsi** [comment] 2018-02-02 16:15
Running into the same issue
